# ---------------------------------------------------
# T3 Semantic Harmonization Configuration
# ---------------------------------------------------
names_keep: null
count_rows_flag: true # what use?

# ---------------------------------------------------
# Clean previous run
# ---------------------------------------------------
cleanup:
  intermediate_data_file: true
  
# ---------------------------------------------------  
# T3 directories
# ---------------------------------------------------
T3:
  name: "study_design"
  root: transformations/T3_study_design
  intermediate: intermediate_data_file
  config: configuration
  source_code: source_code
  sql_dir: source_code/sql
  temp_db: intermediate_data_file/temp.duckdb
  functions: source_code/functions


# ---------------------------------------------------
# T3 Substeps
# ---------------------------------------------------
substep:
  create_univariate_episodes: true
  create_multivariate_episodes: false
