config_refs:
  project: configuration/config_project.yaml
  t2: configuration/config_T2.yaml

helpers:
  - tests/helper.R

child_pugh:
  data_dir: tests/testthat/data/childpugh

egfr_uacr:
  data_dir: tests/testthat/data/egfr_uacr

hemtransplant:
  data_dir: tests/testthat/data/hemtransplant

univariate_episodes:
  data_dir: tests/testthat/data/univariate_episodes
  start_study_date: "2024-09-01"
  end_study_date: "2024-12-31"

multivariate_episodes:
  data_dir: tests/testthat/data/multivariate_episodes
